config/routes.rb
Rails.application.routes.draw do
  resources :places
  resources :users
  resources :topics do
    resources :quotes
  end
  resources :quotes
  resources :sessions

  root 'topics#index'
  
  get '/quotes/:id/add', to: 'quotes#add', as: 'add_quote'
  get '/quotes/:id/link', to: 'quotes#link', as: 'link_quote'
  post '/quotes/:id/link', to: 'quotes#post_link', as: 'post_link_quote'
  post '/quotes/:id/link_clipboard', to: 'quotes#post_link_clipboard', as: 'post_link_clipboard'
  post '/quotes/:id/vote', to: 'quotes#vote', as: 'post_vote'

  post '/places/:id/follow', to: 'places#follow', as: 'follow_place'
  post '/places/:id/unfollow', to: 'places#unfollow', as: 'unfollow_place'

  post '/topics/:id/follow', to: 'topics#follow', as: 'follow_topic'
  post '/topics/:id/unfollow', to: 'topics#unfollow', as: 'unfollow_topic'

  post '/users/:id/follow', to: 'users#follow', as: 'follow_user'
  post '/users/:id/unfollow', to: 'users#unfollow', as: 'unfollow_user'

  get '/users/:id/clipboard', to: 'users#clipboard', as: 'clipboard'
  delete '/users/:id/clipboard', to: 'users#clear_clipboard', as: 'clear_clipboard'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#delete'
  get '/auth/facebook/callback' => 'sessions#create'

  get '/forbidden', to: 'errors#forbidden', as: 'forbidden'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/quote.rb
class Quote < ApplicationRecord
    has_many :supported_quotes, foreign_key: :supporter_id, class_name: 'Support'
    has_many :supportees, through: :supported_quotes
    has_many :supporting_quotes, foreign_key: :supportee_id, class_name: 'Support'
    has_many :supporters, through: :supporting_quotes

    has_many :opposed_quotes, foreign_key: :opposer_id, class_name: 'Oppose'
    has_many :opposees, through: :opposed_quotes
    has_many :opposing_quotes, foreign_key: :opposee_id, class_name: 'Oppose'
    has_many :opposers, through: :opposing_quotes

    belongs_to :user
    belongs_to :topic

    has_many :clipboards_quotes
    has_many :clipboards, through: :clipboards_quotes
    
    validates :text, length: { in: 200..1000 }
    validates :source_url, format: { with: /\A(?:(?:https?|ftp):\/\/)(?:\S+(?::\S*)?@)?(?:(?!10(?:\.\d{1,3}){3})(?!127(?:\.\d{1,3}){3})(?!169\.254(?:\.\d{1,3}){2})(?!192\.168(?:\.\d{1,3}){2})(?!172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\u00a1-\uffff0-9]+-?)*[a-z\u00a1-\uffff0-9]+)(?:\.(?:[a-z\u00a1-\uffff0-9]+-?)*[a-z\u00a1-\uffff0-9]+)*(?:\.(?:[a-z\u00a1-\uffff]{2,})))(?::\d{2,5})?(?:\/[^\s]*)?\z/i, 
        message: "is not a valid url" }
    validates_presence_of :topic_id, message: " must be between 1 and 40 characters: letters, numbers, or spaces"

    def topic_name
        self.topic ? self.topic.name : nil
    end

    def topic_place
        self.topic ? self.topic.place : nil
    end

    def support_count
        supporters.length
    end

    def oppose_count
        opposers.length
    end

    def rating
        support_count - oppose_count
    end

    def sitename
        shortened_url = URI.parse(source_url).host
        number_of_dots = shortened_url.split(//).select { |l| l == '.' }
        if !number_of_dots.length == 2
            shortened_url = shortened_url.prepend('www.')
        end
        shortened_url.match(/(?<=\.)(.*?)(?=\.)/)[0]
    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
    before_action :require_login, only: [:new, :create, :add, :link, :post_link]
    
    def index
        redirect_to root_path
    end
    
    def show
        @quote = Quote.find(params[:id])
        if current_user
            @clipboard = current_user.clipboard
        end
    end

    def new
        if params[:topic_id]
            @quote = Quote.new(topic_id: params[:topic_id])
        else
            @quote = Quote.new
        end
    end

    def create
        @quote = current_user.quotes.new(quote_params)
        @quote.topic = Topic.find_or_create_by(name: namify(params[:quote][:topic_name]), place_id: params[:quote][:topic_place])
        if @quote.save
            redirect_to quote_path(@quote)
        else
            @quote.topic.destroy if @quote.topic.quotes.empty?
            render :new
        end
    end

    def add
        @quote = Quote.find(params[:id])
        if !current_user.clipboard.quotes.include?(@quote)
            current_user.clipboard.quotes << @quote
        end
        redirect_to clipboard_path(current_user)
    end

    def link
        @quote = Quote.find(params[:id])
        @clipboard = current_user.clipboard
    end

    def post_link
        @quote = Quote.find(params[:id])
        new_quote = Quote.create(user: current_user, topic: @quote.topic, text: params[:text], source_url: params[:source_url])
        if params[:type] == "support"
            @quote.supporters << new_quote
        elsif params[:type] == "oppose"
            @quote.opposers << new_quote
        end
        redirect_to quote_path(@quote)
    end

    def post_link_clipboard
        @quote = Quote.find(params[:id])
        linked_quote = Quote.find(params[:linked_quote_id])
        if params[:type] == "support"
            if !@quote.supporters.include?(linked_quote) && linked_quote != @quote
                @quote.supporters << linked_quote
            end
        elsif params[:type] == "oppose"
            if !@quote.opposers.include?(linked_quote) && linked_quote != @quote
                @quote.opposers << linked_quote
            end
        end
        redirect_to quote_path(@quote)
    end

    def destroy
        @quote = Quote.find(params[:id])
        topic = @quote.topic
        if @quote.user == current_user && @quote.supporters.empty? && @quote.opposers.empty?
            @quote.destroy
            if topic.quotes.empty?
                topic.destroy
                redirect_to topics_path
            else
                redirect_to topic_path(topic)
            end
        else
            flash[:alert] = "sorry, but only a quote with no linked quotes can be deleted."
            redirect_to quote_path(@quote)
        end
    end

    def vote
    end

    private

    def quote_params
        params.require(:quote).permit(:text, :source_url)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
    
end

app/views/quotes/link.html.erb
<div class="quote_show">
    <h3 class="quote_text"><%= @quote.text %></h3>
    <p class="source_link"> - <%= link_to "source: #{@quote.sitename}", @quote.source_url %></p>
</div>
<div class="link_new_quote_form">
    <%= form_with url: post_link_quote_path(@quote), class: "new_quote" do |f| %>
        <%= label_tag nil, " link a new quote:", id: "link_new_quote_instructions" %><br><br>
        <%= radio_button_tag :type, "support" %>
        <%= label_tag :type_support, "supporting", style: "font-size: 16px; font-weight: bold" %><br>
        <%= radio_button_tag :type, "oppose" %>
        <%= label_tag :type_oppose, "opposing", style: "font-size: 16px; font-weight: bold" %><br><br>
        <%= f.text_area :text, placeholder: "quote text:" %><br>
        <%= f.text_field :source_url, placeholder: "source url:" %><br>
        <%= f.submit "link quote" %>
    <% end %>
</div>
<p class="clipboard_instructions"> or link from the clipboard: </p>
<% if @clipboard.quotes.empty? %>
    <p class="empty_clipboard"> the clipboard is empty. </p>
<% end %>
<div class="row">
<% @clipboard.clipboard_topic_quotes(@quote.topic).each do |quote| %>
    <div class="column">
        <p class="quote_text"><%= quote.text %></p>
        <%= form_with url: post_link_clipboard_path(@quote), class: "clipboard_link_form" do |f| %>
            <%= hidden_field_tag :linked_quote_id, quote.id %>
            <%= radio_button_tag :type, "support" %>
            <%= label_tag :type_support, "supporting", style: "font-weight: bold" %><br>
            <%= radio_button_tag :type, "oppose" %>
            <%= label_tag :type_oppose, "opposing", style: "font-weight: bold" %><br><br>
            <%= f.submit "link quote" %>
        <% end %>
    </div>
<% end %>

app/views/quotes/new.html.erb
<div class="new_quote">
  <% if @quote.errors.any? %>
  <div id="error_explanation">
    <h4>
      some errors prohibited this quote from being saved:
    </h4>
    <ul>
      <% @quote.errors.full_messages.each do |msg| %>
        <li><%= msg.downcase %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <%= form_for @quote, class: "new_quote" do |f| %>
  <%= f.text_field :topic_name, placeholder: "topic:", id: "new_topic_form_text_field" %>
  <%= f.collection_select :topic_place, Place.all, :id, :name, id: "new_topic_form_collection_select" %><br><br>
  <%= f.text_area :text, placeholder: "quote text:", value: @quote.text %><br>
  <%= f.text_field :source_url, placeholder: "source url:", value: @quote.source_url %><br>
  <%= f.submit "create quote" %>
  <% end %>
</div>

app/views/quotes/show.html.erb
<% if flash[:alert] %>
    <div class="alert">
        <p><%= flash[:alert] %></p>
    </div>
<% end %>
<br>
<h2 class="place_title"><%= link_to @quote.topic.name, topic_path(@quote.topic) %> (<%= @quote.topic.place.name %>)</h2>
<div class="quote_show">
    <h3 class="quote_text"><%= @quote.text %></h3>
    <p class="quote_show_support_count" id="quote_user">- <%= link_to @quote.user.username, user_path(@quote.user) %></p>
    <p class="source_link"> - <%= link_to "source: #{@quote.sitename}", @quote.source_url %></p>
    <br>
    <p class="quote_show_support_count" id="top"><%= @quote.support_count %> supporting</p>
    <p class="source_link"> - <%= link_to "add to clipboard", add_quote_path(@quote) %></p>
    <br>
    <p class="quote_show_support_count" id="bottom"><%= @quote.oppose_count %> opposing</p>
    <p class="add_source_link"> - <%= link_to "link a quote", link_quote_path(@quote), class: "add_source_link" %></p>
    <br>
    <% if current_user == @quote.user %>
        <%= form_with model: @quote, method: 'delete', class: "source_link" do |f| %>
            <%= f.submit "delete quote" %>
        <% end %>
    <% end %>
</div>
<div class="quote_row">
    <div class="for_column">
        <div class="title">
            <h4>supporting quotes:</h4>
        </div>
        <% @quote.supporters.each do |quote| %>
            <div class="for_quote">
                <p class="quote_text"><%= quote.text %></p>
                <%= link_to "source: #{quote.sitename}", quote.source_url, class: "source" %>
                <%= link_to "see quote", quote_path(quote), class: "see_quote" %>
            </div>
        <% end %>
    </div>
    <div class="against_column">
        <div class="title">
            <h4>opposing quotes:</h4>
        </div>
        <% @quote.opposers.each do |quote| %>
            <div class="against_quote">
                <p class="quote_text"><%= quote.text %></p>
                <%= link_to "source: #{quote.sitename}", quote.source_url, class: "source" %>
                <%= link_to "see quote", quote_path(quote), class: "see_quote" %>
            </div>
        <% end %>
    </div>
</div>