config/routes.rb
Rails.application.routes.draw do
  resources :places
  resources :users
  resources :topics do
    resources :quotes
  end
  resources :quotes
  resources :sessions

  root 'topics#index'
  
  get '/quotes/:id/add', to: 'quotes#add', as: 'add_quote'
  get '/quotes/:id/link', to: 'quotes#link', as: 'link_quote'
  post '/quotes/:id/link', to: 'quotes#post_link', as: 'post_link_quote'
  post '/quotes/:id/link_clipboard', to: 'quotes#post_link_clipboard', as: 'post_link_clipboard'
  post '/quotes/:id/vote', to: 'quotes#vote', as: 'post_vote'

  post '/places/:id/follow', to: 'places#follow', as: 'follow_place'
  post '/places/:id/unfollow', to: 'places#unfollow', as: 'unfollow_place'

  post '/topics/:id/follow', to: 'topics#follow', as: 'follow_topic'
  post '/topics/:id/unfollow', to: 'topics#unfollow', as: 'unfollow_topic'

  post '/users/:id/follow', to: 'users#follow', as: 'follow_user'
  post '/users/:id/unfollow', to: 'users#unfollow', as: 'unfollow_user'

  get '/users/:id/clipboard', to: 'users#clipboard', as: 'clipboard'
  delete '/users/:id/clipboard', to: 'users#clear_clipboard', as: 'clear_clipboard'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#delete'
  get '/auth/facebook/callback' => 'sessions#create'

  get '/forbidden', to: 'errors#forbidden', as: 'forbidden'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :quotes
    has_many :user_topics
    has_many :users, through: :user_topics
    belongs_to :place

    validates :name, format: { with: /\A(?:[A-Za-z]+)(?:[A-Za-z0-9 _]*)\z/,
        message: "of topic only allows letters, numbers, and spaces" }
    validates :name, length: { in: 1..40,
        message: "of topic must be between 1 and 40 characters" }
    
    def last_3_quotes
        lowest_rated = self.quotes.sort_by { |quote| quote.rating }
        highest_rated = lowest_rated.reverse
        least_recent = highest_rated.sort_by { |quote| quote.created_at }
        least_recent.reverse
    end

    def last_3_quotes_limit
        lowest_rated = self.quotes.sort_by { |quote| quote.rating }
        highest_rated = lowest_rated.reverse
        least_recent = highest_rated.sort_by { |quote| quote.created_at }
        least_recent.reverse.take(3)
    end


    def topic_last_3_quotes(user)
        last_3_quotes.select { |quote| quote.user == user }
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    def index
        if params[:filter].blank? || params[:filter] == "following"
            if logged_in? && !current_user.topics.empty?
                @topics = current_user.topics.most_recent
            else
                @topics = Topic.all.most_recent
            end
        elsif params[:filter] == "all"
            @topics = Topic.all.most_recent
        else
            place = Place.find_by(name: params[:filter])
            @topics = place.topics.most_recent
        end
    end

    def show
        @topic = Topic.find(params[:id])
        @quotes = @topic.last_3_quotes
    end

    def follow
        @topic = Topic.find(params[:id])
        current_user.topics << @topic
        redirect_to topics_path
    end

    def unfollow
        @topic = Topic.find(params[:id])
        current_user.topics.delete(@topic)
        redirect_to topics_path
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
    
end

app/views/topics/index.html.erb
<%= link_to "new quote", new_quote_path, class: "new_quote" %>
<% if logged_in? %>
    <div class="topics_index_top_pane">
            <%= form_tag("/topics", method: "get", class: "topics_filter") do %>
                <%= select_tag "filter", options_for_select(["following", "all", current_user.places.collect { |p| p.name }].flatten, selected: params[:filter]) %>
                <%= submit_tag "filter", style: "font-weight: bold"  %>
            <% end %>
    </div>
<% end %>
<% @topics.each do |topic| %>
    <br>
    <h2 class="place_title"><%= link_to topic.name, topic_path(topic) %> (<%= topic.place.name %>)</h2>
    <% if logged_in? %>
        <% if !current_user.topics.include?(topic) %>
            <%= form_with url: follow_topic_path(topic), class: "follow" do %>
                <%= submit_tag("follow") %>
            <% end %>
        <% else %>
            <%= form_with url: unfollow_topic_path(topic), class: "follow" do %>
                <%= submit_tag("unfollow") %>
            <% end %>
        <% end %>
    <% end %>
    <br><br>
    <div class="topic_row">
    <% topic.last_3_quotes_limit.each do |quote| %>
        <div class="topic_index_column">
            <p class="quote_text"><%= quote.text %></p>
            <%= link_to "source: #{quote.sitename}", quote.source_url, class: "source" %>
            <%= link_to "see quote", quote_path(quote), class: "see_quote" %><br>
            <p class="support_count">supporting: <%= quote.support_count %></p>
            <p class="support_count">opposing: <%= quote.oppose_count %></p>
        </div>
    <% end %>
    <% if topic.quotes.length > 3 %>
        <div class="break_column"></div>
        <%= link_to "see more...", topic_path(topic), class: "see_more" %>
    <% end %>
    </div>
<% end %>

app/views/topics/new.html.erb
<%= form_for @topic, class: "new_quote" do |f| %>
    <%= f.text_field :name, placeholder: "topic:", id: "new_topic_form_text_field" %>
    <%= f.collection_select :place_id, Place.all, :id, :name, id: "new_topic_form_collection_select" %><br><br>
    <%= f.submit "create topic" %>
<% end %>

app/views/topics/show.html.erb
<div class="centered_clipboard_title">
<h2 class="clipboard_title"><%= @topic.name %></h2>
<% if logged_in? %>
    <% if !current_user.topics.include?(@topic) %>
        <%= form_with url: follow_topic_path(@topic), class: "show_follow" do %>
            <%= submit_tag("follow") %>
        <% end %>
    <% else %>
        <%= form_with url: unfollow_topic_path(@topic), class: "show_follow" do %>
            <%= submit_tag("unfollow") %>
        <% end %>
    <% end %>
<% end %>
</div>
<%= link_to "new quote", new_topic_quote_path(@topic), class: "new_quote_topic" %>
<div class="topics_index_top_pane">
</div>
<div class="row">
<% @quotes.each do |quote| %>
    <div class="clipboard_column">
        <p class="quote_text"><%= quote.text %></p>
        <%= link_to "source: #{quote.sitename}", quote.source_url, class: "source" %>
        <%= link_to "see quote", topic_quote_path(@topic, quote), class: "see_quote" %>
        <p class="support_count">supporting: <%= quote.support_count %></p>
        <p class="support_count">opposing: <%= quote.oppose_count %></p>
    </div>
<% end %>