config/routes.rb
Rails.application.routes.draw do
  resources :places
  resources :users
  resources :topics do
    resources :quotes
  end
  resources :quotes
  resources :sessions

  root 'topics#index'
  
  get '/quotes/:id/add', to: 'quotes#add', as: 'add_quote'
  get '/quotes/:id/link', to: 'quotes#link', as: 'link_quote'
  post '/quotes/:id/link', to: 'quotes#post_link', as: 'post_link_quote'
  post '/quotes/:id/link_clipboard', to: 'quotes#post_link_clipboard', as: 'post_link_clipboard'
  post '/quotes/:id/vote', to: 'quotes#vote', as: 'post_vote'

  post '/places/:id/follow', to: 'places#follow', as: 'follow_place'
  post '/places/:id/unfollow', to: 'places#unfollow', as: 'unfollow_place'

  post '/topics/:id/follow', to: 'topics#follow', as: 'follow_topic'
  post '/topics/:id/unfollow', to: 'topics#unfollow', as: 'unfollow_topic'

  post '/users/:id/follow', to: 'users#follow', as: 'follow_user'
  post '/users/:id/unfollow', to: 'users#unfollow', as: 'unfollow_user'

  get '/users/:id/clipboard', to: 'users#clipboard', as: 'clipboard'
  delete '/users/:id/clipboard', to: 'users#clear_clipboard', as: 'clear_clipboard'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#delete'
  get '/auth/facebook/callback' => 'sessions#create'

  get '/forbidden', to: 'errors#forbidden', as: 'forbidden'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    acts_as_voter

    has_many :user_topics
    has_many :topics, through: :user_topics
    has_many :user_places
    has_many :places, through: :user_places
    has_many :quotes

    has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
    has_many :followees, through: :followed_users
    has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
    has_many :followers, through: :following_users

    has_one :clipboard

    validates :username, format: { with: /\A(?=.{2,20}$)(?![_.])(?!.*[_.]{2})[a-zA-Z0-9.]+(?<![_.])\z/,
        message: "is not a valid username. 2-20 characters: letters, numbers, and dots" }
    validates :username, uniqueness: true

    def self.most_quotes
        ascending = self.all.sort_by { |user| user.quotes.count }
        ascending.reverse
    end

    def quote_topics
        quotes.collect { |quote| quote.topic }
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, only: [:clipboard]
    
    def new
        @user = User.new
    end

    def create
        if User.find_by(username: user_params[:username])
            flash[:alert] = "username is taken"
            redirect_to '/signup'
        else
            @user = User.new(user_params)
            if @user.save
                @user.update(clipboard: Clipboard.create)
                session[:user_id] = @user.id
                redirect_to root_path
            else
                render :new
            end
        end
    end

    def index
        if logged_in?
            @followees = current_user.followees
        end
            @users = User.most_quotes
    end

    def show
        @user = User.find(params[:id])
    end

    def clipboard
        user = User.find(params[:id])
        @clipboard = user.clipboard
    end

    def clear_clipboard
        user = User.find(params[:id])
        @clipboard = user.clipboard
        @clipboard.quotes.clear
        redirect_to clipboard_path(user)
    end

    def follow
        user = User.find(params[:id])
        current_user.followees << user
        redirect_to users_path
    end

    def unfollow
        user = User.find(params[:id])
        current_user.followees.delete(user)
        redirect_to users_path
    end

    private

    def user_params
        params.require(:user).permit(:username, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/clipboard.html.erb
<h2 class="clipboard_title_real">clipboard</h2>
<div class="clear_clipboard">
    <%= form_with url: clear_clipboard_path(current_user), method: 'delete' do %>
        <%= submit_tag("clear clipboard") %>
    <% end %>
</div>
<div class="topics_index_top_pane">
</div>
<% @clipboard.clipboard_topics.each do |topic| %>
    <br>
    <h2 class="place_title"><%= topic.name %></h2>
    <br>
    <br>
    <div class="row">
    <% @clipboard.clipboard_topic_quotes(topic).each do |quote| %>
        <div class="clipboard_column">
            <p class="quote_text"><%= quote.text %></p>
            <%= link_to "source: #{quote.sitename}", quote.source_url, class: "source" %>
            <%= link_to "see quote", quote_path(quote), class: "see_quote" %>
            <p class="support_count">supporting: <%= quote.support_count %></p>
            <p class="support_count">opposing: <%= quote.oppose_count %></p>
        </div>
    <% end %>
    </div>
<% end %>

app/views/users/index.html.erb
<% if logged_in? && !@followees.empty? %>
    <h3 id="following_header">following:</h3>
    <% @followees.each do |followee| %>
        <div class="centered_clipboard_title_place">
            <h2 class="clipboard_title"><%= link_to followee.username, user_path(followee) %></h2>
            <% if logged_in? %>
                <% if !current_user.followees.include?(followee) %>
                    <%= form_with url: follow_user_path(followee), class: "follow" do %>
                        <%= submit_tag("follow") %>
                    <% end %>
                <% else %>
                    <%= form_with url: unfollow_user_path(followee), class: "follow" do %>
                        <%= submit_tag("unfollow") %>
                    <% end %>
                <% end %>
            <% end %>
        </div>
        <% followee.quote_topics.uniq.each do |topic| %>
            <br>
            <h2 class="place_title"><%= link_to topic.name, topic_path(topic) %></h2>
            <br>
            <br>
            <div class="topic_row"> 
                <% topic.topic_last_3_quotes(followee).each do |quote| %>
                    <div class="topic_index_column">
                        <p class="quote_text"><%= quote.text %></p>
                        <%= link_to "source: #{quote.sitename}", quote.source_url, class: "source" %>
                        <%= link_to "see quote", quote_path(quote), class: "see_quote" %><br>
                        <p class="support_count">supporting: <%= quote.support_count %></p>
                        <p class="support_count">opposing: <%= quote.oppose_count %></p>
                    </div>
                <% end %>
                <% if followee.quotes.length > 3 %>
                    <div class="break_column"></div>
                    <%= link_to "see more...", topic_path(topic), class: "see_more" %>
                <% end %>
                <br>
            </div>
        <% end %>
    <% end %>
    <h3 id="following_header">all users:</h3>
<% elsif logged_in? && @followees.empty? %>
    <h3 id="not_following_users"> you aren't following any users </h3>
    <div class="topics_index_top_pane"></div>
    <h3 id="following_header">all users:</h3>
<% end %>
<% @users.each do |user| %>
    <div class="centered_clipboard_title_place">
        <h2 class="clipboard_title"><%= link_to user.username, user_path(user) %></h2>
        <% if logged_in? %>
            <% if !current_user.followees.include?(user) %>
                <%= form_with url: follow_user_path(user), class: "follow" do %>
                    <%= submit_tag("follow") %>
                <% end %>
            <% else %>
                <%= form_with url: unfollow_user_path(user), class: "follow" do %>
                    <%= submit_tag("unfollow") %>
                <% end %>
            <% end %>
        <% end %>
    </div>
    <% user.quote_topics.uniq.each do |topic| %>
        <br>
        <h2 class="place_title"><%= link_to topic.name, topic_path(topic) %></h2>
        <br>
        <br>
        <div class="topic_row"> 
            <% topic.topic_last_3_quotes(user).each do |quote| %>
                <div class="topic_index_column">
                    <p class="quote_text"><%= quote.text %></p>
                    <%= link_to "source: #{quote.sitename}", quote.source_url, class: "source" %>
                    <%= link_to "see quote", quote_path(quote), class: "see_quote" %><br>
                    <p class="support_count">supporting: <%= quote.support_count %></p>
                    <p class="support_count">opposing: <%= quote.oppose_count %></p>
                </div>
            <% end %>
            <% if user.quotes.length > 3 %>
                <div class="break_column"></div>
                <%= link_to "see more...", topic_path(topic), class: "see_more" %>
            <% end %>
            <br>
        </div>
    <% end %>
<% end %>

app/views/users/new.html.erb
<% if flash[:alert] %>
    <div class="alert"><%= flash[:alert] %></div>
<% end %>
<% if @user.errors.any? %>
<div class="new_quote">
  <div id="error_explanation">
    <h4>
      some errors prohibited this user from being saved:
    </h4>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg.downcase %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>
<div class="login_container">
    <div class="login">
        <%= form_for @user do |f| %>
            <%= f.text_field :username, placeholder: "username:" %><br><br> 
            <%= f.password_field :password, placeholder: "password:" %>
            <%= f.submit "submit", style: "display: inline" %>
        <% end %>
    </div>
</div>
<% if false %>
<div class="login_container">
  <%= link_to 'log in with Facebook', '/auth/facebook', class: "facebook_login" %>
</div>
<% end %>

app/views/users/show.html.erb
<div class="centered_clipboard_title_place">
    <h2 class="clipboard_title"><%= @user.username %></h2>
    <% if logged_in? %>
        <% if !current_user.followees.include?(@user) %>
            <%= form_with url: follow_user_path(@user), class: "follow" do %>
                <%= submit_tag("follow") %>
            <% end %>
        <% else %>
            <%= form_with url: unfollow_user_path(@user), class: "follow" do %>
                <%= submit_tag("unfollow") %>
            <% end %>
        <% end %>
    <% end %>
</div>
<% @user.quote_topics.uniq.each do |topic| %>
    <br>
    <h2 class="place_title"><%= link_to topic.name, topic_path(topic) %></h2>
    <br>
    <br>
    <div class="topic_row"> 
        <% topic.topic_last_3_quotes(@user).each do |quote| %>
            <div class="topic_index_column">
                <p class="quote_text"><%= quote.text %></p>
                <%= link_to "source: #{quote.sitename}", quote.source_url, class: "source" %>
                <%= link_to "see quote", quote_path(quote), class: "see_quote" %><br>
                <p class="support_count">supporting: <%= quote.support_count %></p>
                <p class="support_count">opposing: <%= quote.oppose_count %></p>
            </div>
        <% end %>
        <% if @user.quotes.length > 3 %>
            <div class="break_column"></div>
            <%= link_to "see more...", topic_path(topic), class: "see_more" %>
        <% end %>
        <br>
    </div>
<% end %>