config/routes.rb
Rails.application.routes.draw do
  resources :places
  resources :users
  resources :topics do
    resources :quotes
  end
  resources :quotes
  resources :sessions

  root 'topics#index'
  
  get '/quotes/:id/add', to: 'quotes#add', as: 'add_quote'
  get '/quotes/:id/link', to: 'quotes#link', as: 'link_quote'
  post '/quotes/:id/link', to: 'quotes#post_link', as: 'post_link_quote'
  post '/quotes/:id/link_clipboard', to: 'quotes#post_link_clipboard', as: 'post_link_clipboard'
  post '/quotes/:id/vote', to: 'quotes#vote', as: 'post_vote'

  post '/places/:id/follow', to: 'places#follow', as: 'follow_place'
  post '/places/:id/unfollow', to: 'places#unfollow', as: 'unfollow_place'

  post '/topics/:id/follow', to: 'topics#follow', as: 'follow_topic'
  post '/topics/:id/unfollow', to: 'topics#unfollow', as: 'unfollow_topic'

  post '/users/:id/follow', to: 'users#follow', as: 'follow_user'
  post '/users/:id/unfollow', to: 'users#unfollow', as: 'unfollow_user'

  get '/users/:id/clipboard', to: 'users#clipboard', as: 'clipboard'
  delete '/users/:id/clipboard', to: 'users#clear_clipboard', as: 'clear_clipboard'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#delete'
  get '/auth/facebook/callback' => 'sessions#create'

  get '/forbidden', to: 'errors#forbidden', as: 'forbidden'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/place.rb
class Place < ApplicationRecord
    has_many :user_places
    has_many :users, through: :user_places
    has_many :topics

    def first_5_topics
        self.topics.limit(5).to_a
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
    before_action :require_login, only: [:follow]
    
    def index
        @places = Place.all
    end

    def show
        @place = Place.find(params[:id])
    end

    def follow
        @place = Place.find(params[:id])
        current_user.places << @place
        redirect_to places_path
    end

    def unfollow
        @place = Place.find(params[:id])
        current_user.places.delete(@place)
        redirect_to places_path
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/index.html.erb
<br>
<% @places.each do |place| %>
    <div class="place_display">
        <h2 class="place_title"><%= link_to place.name, place_path(place) %></h2>
        <% if logged_in? %>
            <% if !current_user.places.include?(place) %>
                <%= form_with url: follow_place_path(place), class: "follow" do %>
                    <%= submit_tag("follow") %>
                <% end %>
            <% else %>
                <%= form_with url: unfollow_place_path(place), class: "follow" do %>
                    <%= submit_tag("unfollow") %>
                <% end %>
            <% end %>
        <% end %>
        <ul class="place_topics">
            <% place.first_5_topics.each do |topic| %>
                <li><%= link_to topic.name, topic_path(topic) %></li>
            <% end %>
            <% if place.topics.length > 5 %>
                <li><%= link_to "see more...", place_path(place) %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/places/show.html.erb
<div class="centered_clipboard_title_place">
<h2 class="clipboard_title"><%= @place.name %></h2>
<% if logged_in? %>
    <% if !current_user.places.include?(@place) %>
        <%= form_with url: follow_place_path(@place), class: "show_follow" do %>
            <%= submit_tag("follow") %>
        <% end %>
    <% else %>
        <%= form_with url: unfollow_place_path(@place), class: "show_follow" do %>
            <%= submit_tag("unfollow") %>
        <% end %>
    <% end %>
<% end %>
</div>
<% @place.topics.each do |topic| %>
    <br>
    <h2 class="place_title"><%= link_to topic.name, topic_path(topic) %></h2>
    <% if logged_in? %>
        <% if !current_user.topics.include?(topic) %>
            <%= form_with url: follow_topic_path(topic), class: "follow" do %>
                <%= submit_tag("follow") %>
            <% end %>
        <% else %>
            <%= form_with url: unfollow_topic_path(topic), class: "follow" do %>
                <%= submit_tag("unfollow") %>
            <% end %>
        <% end %>
    <% end %>
    <br><br>
    <div class="topic_row">
    <% topic.last_3_quotes_limit.each do |quote| %>
        <div class="topic_index_column">
            <p class="quote_text"><%= quote.text %></p>
            <%= link_to "source: #{quote.sitename}", quote.source_url, class: "source" %>
            <%= link_to "see quote", quote_path(quote), class: "see_quote" %><br>
            <p class="support_count">supporting: <%= quote.support_count %></p>
            <p class="support_count">opposing: <%= quote.oppose_count %></p>
        </div>
    <% end %>
    <% if topic.quotes.length > 3 %>
        <div class="break_column"></div>
        <%= link_to "see more...", topic_path(topic), class: "see_more" %>
    <% end %>
    </div>
<% end %>